name: Continuous Training
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason: 
        description: Why to run this?
        required: false
        default: running CT
jobs:
  continuous-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Train model
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}}
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          export GDRIVE_CREDENTIALS_DATA=$(python utilities/setter.py)
          dvc remote modify mymodel --local gdrive_service_account_json_file_path path.json
          dvc remote default mymodel
          dvc pull model/model.pkl
          dvc unprotect model/model.pkl
          dvc repro -f 
          echo "Training Completed"
          dvc add model/model.pkl.dvc -r mymodel --to-remote
          dvc push model/model.pkl.dvc -r mymodel
      - name: Commit .dvc file changes
        run: |
          git config --local user.email "encinaesteban27@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: iterative/setup-cml@v1
      - name: Push metrics
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat report.txt >>report.md
          cml-publish prediction_behavior.png --md >> report.md
          cml-send-comment report.md
       

